#!/usr/local/bin/php
<?php
  $nemsserver = '127.0.0.1';

  function query($query) {
    global $nemsserver;
    $url = 'http://' . $nemsserver . '/nems-api/' . $query;
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    if ($response = curl_exec($ch)) {
      $result = json_decode($response);
    } else {
      $result = json_encode(array('error'=>'invalid query or server not responding'));
    }
    curl_close($ch);
    return ($result);
  }

//  $hosts = query('hosts');
//  $services = query('services');
//print_r($hosts);
//print_r($services);

$states = query('hosts?Columns=name,state');
/*
  0 = OK
  1 = WARNING
  2 = CRITICAL
  3 = UNKNOWN
*/

print_r($states);


?>

