#!/bin/bash

if [[ -e /usr/local/bin/nems-info ]]; then
  platform=$(/usr/local/bin/nems-info platform)
else
  platform=0 # Assume this is a raw Pi distro
fi

apt update
apt -y install php7.3 apache2 libapache2-mod-php php-curl

tmpdir=`mktemp -d -p /tmp/`

# Activate /nems-tools Apache conf
ln -s /root/nems/nems-tools/install/apache2.conf /etc/apache2/conf-available/nems-tools.conf
a2enconf nems-tools

git config --global user.email "nems@category5.tv"
git config --global user.name "NEMS Tools"

 # Make a symlink to the PHP interpreter if it doesn't exist in /usr/local/bin
 if [[ ! -e /usr/local/bin/php ]]; then
  if [[ -e /usr/bin/php ]]; then
   ln -s /usr/bin/php /usr/local/bin/php
  fi
 fi

# Setup GPIO connections on Raspberry Pi
if (( $platform >= 0 )) && (( $platform <= 9 )); then
  cd /root/nems/
  git clone git://git.drogon.net/wiringPi
  cd wiringPi
  ./build
fi


# Add new cron entries

  # Dump current crontab to tmp file
  crontab -l > $tmpdir/cron.tmp

  # Install the NEMS Tools GPIO Extender daemon.
  if ! grep -q "NEMS0016" $tmpdir/cron.tmp; then
    printf "\n# NEMS Tools GPIO Extender Server NEMS0016\n@reboot /root/nems/nems-tools/gpio-extender/gpioe-server > /dev/null 2>&1\n" >> $tmpdir/cron.tmp
    cronupdate=1
    # Run it
    /root/nems/nems-tools/gpio-extender/gpioe-server > /dev/null 2>&1 &
  fi

  # Import revised crontab
  if [[ "$cronupdate" == "1" ]]
  then
    crontab $tmpdir/cron.tmp
  fi

  # Remove temp file
  rm $tmpdir/cron.tmp

# /Add new cron entries

# Reload apache2
systemctl reload apache2
